// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSCS-Lensgenerator")>]
[<assembly: AssemblyProductAttribute("FSCS-Lensgenerator")>]
[<assembly: AssemblyDescriptionAttribute("FSCS-LensGenerator: generate lenses/optics for F# projects")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSCS-Lensgenerator"
    let [<Literal>] AssemblyProduct = "FSCS-Lensgenerator"
    let [<Literal>] AssemblyDescription = "FSCS-LensGenerator: generate lenses/optics for F# projects"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
